name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # on events
  release:
    types: 
        - created

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...
    
    - name: Vet
      run: go vet ./...
      
    - name: Test
      run: |
       go test -v ./internal/...
       go test -v ./pkg/request/...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
        version: v1.29
        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true   

  # workflow name
  generate:
    needs: [build]
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: stormvirux/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, darwin/arm64, windows/amd64'
            package: ''
            name: 'bibrefer'
            compress: 'true'
            dest: './bin'

  
