name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    # on events
  release:
    types: 
        - created

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [debian-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3

    - name: Build
      run: go build -v ./...
    
    - name: Vet
      run: go vet ./...
      
    - name: Test
      run: |
       go test -v ./internal/...
       go test -v ./pkg/request/...

  # workflow name
  generate:
    needs: [build]
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: stormvirux/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, darwin/arm64, windows/amd64'
            package: ''
            name: 'bibrefer'
            compress: 'true'
            dest: './bin'

  
